server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vivo_store?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
  data:
    redis:
      database: 5
      host: 127.0.0.1
      port: 6379
      timeout: 10000

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl